### ISSUE TITLE
Default MulterOptions does not save to storage

### ISSUE THREAD

**Issue by dimbslmh** [jmcdo29/nest-lab#14]
:x: **Does not save to storage:**

- Not providing any `MulterOptions` in `register/registerAsync`.
- Not providing any `localOptions` in `FileInterceptor/FilesInterceptor`.
- Setting `dest` or `storage:  diskStorage({ destination })` in `register/registerAsync`.

:white_check_mark: **Saves to storage:**

- Setting `dest` or `storage:  diskStorage({ destination })` in `FileInterceptor/FilesInterceptor`.

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by dimbslmh** [comment]
I have created a repro: https://github.com/dimbslmh/multeroptions

You will see that only `bird` and `birds` will have a directory created under `upload`. These 2 have `localOptions` set in the `FileInterceptor/FilesInterceptor`. 

You can also try uploading a file and it won't be saved in storage for `cats` and `horses`.

**Comment by jmcdo29** [comment]
Sure enough, good find with this. Thanks for the reproduction as well! Looks like I just need to add in the `MODULE_OPTIONS_TOKEN` to the `exports` of the `FastifyMulterModule`.

**Comment by jmcdo29** [comment]
Fixed with 1.0.2
