### ISSUE TITLE
Question: Using typeschema with nestjs/config

### ISSUE THREAD

**Issue by rubiin** [jmcdo29/nest-lab#31]
Been using @nest-lab/typeschema and it is super awesome as I could switch the underlying validator. I was wondering is there a way to make it work with nestjs/config as well.

**Comment by jmcdo29** [comment]
As all that matters is that there's a [`validate` function](https://docs.nestjs.com/techniques/configuration#custom-validate-function) that gets passed to `ConfigModule.forRoot()` that takes in a config record and passed back the validated config or throws an exception, you could use `@decs/typeschema` directly and use whatever schema library you prefer
