### ISSUE TITLE
Add `repository` entry to `package.json`

### ISSUE THREAD

**Issue by micalevisk** [jmcdo29/nest-lab#7]
Can you please add the following [repository entry](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository) to your `package.json`?

```json
  "repository": {
    "type": "git",
    "url": "https://github.com/jmcdo29/nest-lab.git",
    "directory": "packages/or-guard"
  },
```

to make this repo searchable from https://www.npmjs.com/package/@nest-lab/or-guard

![image](https://user-images.githubusercontent.com/13461315/140520643-ae6dfc2a-5e7f-4485-ba8c-ac1e2e177eda.png)

**Comment by jmcdo29** [comment]
Thanks for pointing this out, I'll get it added. Shame it'll have to be added to npm as a patch for no real code change

**Comment by micalevisk** [comment]
I believe there's a place for a minor refactoring here:

https://github.com/jmcdo29/nest-lab/blob/bc04b4c6d20644f484fd9d8eeb7fcb33baa536be/packages/or-guard/src/lib/or.guard.ts#L63

```diff
- return throwError(err);
+ return throwError(() => err); 
```

![image](https://user-images.githubusercontent.com/13461315/156485244-a3a22e3e-942c-4cb5-8b42-d7f9777edc36.png)

And formatting

https://github.com/jmcdo29/nest-lab/blob/bc04b4c6d20644f484fd9d8eeb7fcb33baa536be/packages/or-guard/src/lib/or.guard.ts#L17

```diff
- import { catchError, last, mergeMap, takeWhile} from 'rxjs/operators';
+ import { catchError, last, mergeMap, takeWhile } from 'rxjs/operators';
```

:smile:

**Comment by jmcdo29** [comment]
Good catch. Also, no clue why I haven't fixed this yet. Whoops

**Comment by micalevisk** [comment]
another one(?) would be on the following part

https://github.com/jmcdo29/nest-lab/blob/bc04b4c6d20644f484fd9d8eeb7fcb33baa536be/packages/or-guard/src/lib/or.guard.ts#L30-L34

as that `guard` private field isn't used anywhere but on `canActivate`, why not just drop it _(micro-optimization here)_

```ts
canActivate(context: ExecutionContext): Observable<boolean> {
 const canActivateReturns: Array<Observable<boolean>> = guards.map(
   (guard) => this.deferGuard(this.modRef.get(guard), context)
 );
}
```

**Comment by jmcdo29** [comment]
Repository was added in 2.1.0. I'll fix the format issue at a later time. The micro optimization was kept out for readability and I don't think it's going to make or break someones time controlled flow, but it's a good call out.
